version: '3.8'

volumes:
  fief-dev-db:

services:
  backend:
    command: uvicorn --host 0.0.0.0 --port 80 --root-path /api --reload fief.app:app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://fief:fiefpassword@db:5432
      - ALLOW_ORIGIN_REGEX=.*localhost:8000.*
      - ROOT_DOMAIN=localhost
      - FIEF_DOMAIN=fief-auth.localhost:8000
      - FIEF_CLIENT_ID=FIEF_CLIENT_ID
      - FIEF_CLIENT_SECRET=FIEF_CLIENT_SECRET

  frontend:
    command: npm run dev
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=http://backend
    volumes:
      - ./frontend:/app

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=fief
      - POSTGRES_PASSWORD=fiefpassword
    volumes:
      - fief-dev-db:/var/lib/postgresql/data

  reverse-proxy:
    ports:
      - "8000:80"
