[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = "furl.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jwcrypto.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "uvicorn.logging.*"
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.coverage.run]
concurrency = ["greenlet"]

[tool.pytest.ini_options]
markers = ["test_data", "account_host", "access_token", "admin_session_token"]
asyncio_mode = "auto"
