[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
exclude = "backend/venv/"

[tool.isort]
profile = "black"

[tool.coverage.run]
concurrency = ["greenlet"]

[tool.pytest.ini_options]
markers = ["user"]
