[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = "furl.*"
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.coverage.run]
concurrency = ["greenlet"]

[tool.pytest.ini_options]
markers = ["test_data"]
