name: "Build admin frontend"
description: "Build the React admin frontend"

inputs:
  github_token:
    description: "GitHub token"
    required: false

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.github_token }}
        submodules: ${{ inputs.github_token && 'recursive' || false }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "14"
    - name: Install dependencies
      shell: bash
      working-directory: admin-frontend
      run: npm ci
    - name: Build
      shell: bash
      working-directory: admin-frontend
      env:
        NODE_ENV: production
        REACT_APP_API_PORT: ""
      run: npm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: admin-frontend-build
        path: |
          admin-frontend/build
