name: "Test admin frontend"
description: "Run the tests for the React admin frontend"

inputs:
  github_token:
    description: "GitHub token"
    required: false

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.github_token }}
        submodules: ${{ inputs.github_token && 'recursive' || false }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "14"
    - name: Install dependencies
      shell: bash
      working-directory: admin-frontend
      run: npm ci
    - name: Lint
      shell: bash
      working-directory: admin-frontend
      run: npm run lint
    # - name: Test
    #   shell: bash
    #   working-directory: admin-frontend
    #   run: npm run test
