name: "Prepare CI"
description: "Action to help checkout the repository with or without the private submodule and restore Pip cache."

inputs:
  github_token:
    description: "GitHub token"
    required: false

runs:
  using: "composite"

  steps:
    - name: "Checkout with private submodules"
      uses: actions/checkout@v3
      if: ${{ inputs.github_token != '' }}
      with:
        token: ${{ inputs.github_token }}
        submodules: recursive
    - name: "Checkout without private submodules"
      uses: actions/checkout@v3
      if: ${{ inputs.github_token == '' }}
      with:
        submodules: false
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
