name: 'Test backend'
description: 'Run the tests for the Python backend'

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
    - name: Lint with isort, black and tryceratops
      shell: bash
      working-directory: backend
      run: |
        isort --check .
        black --check .
        mypy fief/
        tryceratops fief/
    - name: Test with pytest
      shell: bash
      working-directory: backend
      env:
        ENVIRONMENT: development
        UNIT_TESTS: "1"
        DATABASE_URL: postgresql://fief:fiefpassword@localhost:5432
        ROOT_DOMAIN: fief.dev
        ALLOW_ORIGIN_REGEX: http://localhost:3000
        FIEF_DOMAIN: fief-auth.localhost:3000
        FIEF_CLIENT_ID: FIEF_CLIENT_ID
        FIEF_CLIENT_SECRET: FIEF_CLIENT_SECRET
      run: |
        pytest --cov=fief/ --cov-report=term-missing
