name: Check SQLite version

on:
  push:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - shell: bash
      run: |
        python -c "import sqlite3; print(sqlite3.sqlite_version)"
