name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish on PyPi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
    - name: Publish
      working-directory: backend
      env:
        FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
        FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
      run: |
        flit publish
    - name: Update release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: false
        artifacts: backend/dist/*.whl,backend/dist/*.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
