name: Sentry release

on:
  release:
    types: [published]

jobs:
  sentry-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Checkout with private submodules if possible"
        uses: ./.github/actions/checkout
        with:
          github_token: ${{ secrets.GH_GLOBAL_TOKEN }}
      - name: Set raw version variable
        shell: bash
        run: |
          echo "${{ github.ref }}" | sed "s/v/RAW_VERSION=$1/" >>  $GITHUB_ENV
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        with:
          projects: fief-server fief-worker
          environment: production
          version: ${{ env.RAW_VERSION }}
