name: Test

on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: fief
          POSTGRES_PASSWORD: fiefpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: fiefpassword

    strategy:
      fail-fast: false
      matrix:
        include:
          - database_type: POSTGRESQL
            database_host: localhost
            database_port: 5432
            database_username: fief
            database_password: fiefpassword
          - database_type: MYSQL
            database_host: localhost
            database_port: 3306
            database_username: root
            database_password: fiefpassword
          - database_type: SQLITE
            database_host: null
            database_port: null
            database_username: null
            database_password: null

    steps:
    - uses: actions/checkout@v2
    - name: Test backend with ${{ matrix.database_type }} database
      uses: ./.github/actions/test-backend
      with:
        database_type: ${{ matrix.database_type }}
        database_host: ${{ matrix.database_host }}
        database_port: ${{ matrix.database_port }}
        database_username: ${{ matrix.database_username }}
        database_password: ${{ matrix.database_port }}
        database_name: fief

  test-auth-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test auth frontend
      uses: ./.github/actions/test-auth-frontend
