name: Test

on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test backend
      uses: ./.github/actions/test-backend

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test frontend
      uses: ./.github/actions/test-frontend
