name: Test

on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: fief
          POSTGRES_PASSWORD: fiefpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
    - name: Lint with isort, black and tryceratops
      shell: bash
      working-directory: backend
      run: |
        isort --check .
        black --check .
        mypy fief/
        tryceratops fief/
    - name: Test with pytest
      shell: bash
      working-directory: backend
      env:
        ENVIRONMENT: development
        UNIT_TESTS: "1"
        TEST_DATABASE_URL: postgresql://fief:fiefpassword@postgres:5432
        DATABASE_URL: postgresql://fief:fiefpassword@localhost:5432
        ROOT_DOMAIN: fief.dev
        ALLOW_ORIGIN_REGEX: http://localhost:3000
        FIEF_DOMAIN: fief-auth.localhost:3000
        FIEF_BASE_URL: http://localhost:8000
        FIEF_CLIENT_ID: FIEF_CLIENT_ID
        FIEF_CLIENT_SECRET: FIEF_CLIENT_SECRET
      run: |
        pytest --cov=fief/ --cov-report=term-missing

  test-auth-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test auth frontend
      uses: ./.github/actions/test-auth-frontend
