name: Test

on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: fief
          POSTGRES_PASSWORD: fiefpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Test backend
      uses: ./.github/actions/test-backend
      with:
        test_database_url: postgresql://fief:fiefpassword@postgres:5432/fief

  test-auth-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test auth frontend
      uses: ./.github/actions/test-auth-frontend
